### ISSUE TITLE
V3.0.0 C11<stdatomic.h> is not supported, is it OK to use it on a microcontroller?

### ISSUE THREAD

**Issue by cqutyoulang** [MaJerle/lwrb#30]
hi：
  I ported the latest v3.0.0 on top of the STM32F4. The development platform used keil , when compiling it shows cannot open source input file "stdatomic.h":, my compiler does not support C11 syntax.
Define LWRB_DISABLE_ATOMIC , compile can can pass, so I use j it in the microcontroller above to store the serial port to receive data is there any risk. In v2.0.2, the volatile keyword is used, but v3.0.0 does not support it.

**Comment by MaJerle** [comment]
Hi,

normally Atomic and volatile are not the there for the same purpose, basically:

- Volatile will ensure that read and write operations are always from the memory (can be from cache tho), but every read operation will reload the CPU registers
- Atomic ensures that read/write is atomic, especially between several cores.

One of the tricky points is when CPU cannot make a read/write in one bus read. If we focus on STM32F4, you may be fine with disabled ATOMICs because `size_t` is 32-bit on Cortex-M and 32-bit can be written in one cycle.

I am sure Keil supports C11, but it may need to be enabled in their settings.

**Comment by cqutyoulang** [comment]
Thanks for your reply, I understand the Atomic and volatile purpose now, and yes keil supports C11 and needs to be compiled with AC6.
